### ISSUE TITLE
Image path doesn't exists (sic) error for a valid sandbox image path

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#1277]
## Version of Singularity:

2.4.2

### Expected behavior

$ singularity shell /absolute/path/to/a/valid/image
Singularity: Invoking an interactive shell within container..

### Actual behavior

$ singularity shell /absolute/path/to/a/valid/image
ERROR  : Image path doesn't exists (sic)
ABORT  : Retval = 255

### Steps to reproduce behavior

This behavior manifests itself if a container with newer glibc is run on a node with an older kernel. Interestingly, when the user changes to the directory with the container image the correct error is returned:

Singularity: Invoking an interactive shell within container...

FATAL: kernel too old

**Comment by jscook2345** [comment]
@cclerget @jmstover 

This sounds familiar. Perhaps this is fixed in another version of `singularity`?

**Comment by Enhancer01** [comment]
still facing the same issue in 2020. i have tried to uninstall version 2.4.2 but couldn't and it would not update to recent version

**Comment by dtrudg** [comment]
> still facing the same issue in 2020. i have tried to uninstall version 2.4.2 but couldn't and it would not update to recent version

Singularity 2.x is no longer supported. Many distributions do not package an up-to-date supported version of Singularity. We recommend installing from source in that case.

**Comment by Enhancer01** [comment]
> > still facing the same issue in 2020. i have tried to uninstall version 2.4.2 but couldn't and it would not update to recent version
> 
> Singularity 2.x is no longer supported. Many distributions do not package an up-to-date supported version of Singularity. We recommend installing from source in that case.

Thank you for your reply, I have uninstalled and install 3.6.2 from source on Ubuntu WLS. however, Its not responding. I want to use singularity to run OMM_MACSE_v10.01.sif pipeline. I am using Ubuntu 18.04 LTS through the Window Linux Subsystem

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
> > > still facing the same issue in 2020. i have tried to uninstall version 2.4.2 but couldn't and it would not update to recent version
> > 
> > 
> > Singularity 2.x is no longer supported. Many distributions do not package an up-to-date supported version of Singularity. We recommend installing from source in that case.
> 
> Thank you for your reply, I have uninstalled and install 3.6.2 from source on Ubuntu WLS. however, Its not responding. I want to use singularity to run OMM_MACSE_v10.01.sif pipeline. I am using Ubuntu 18.04 LTS through the Window Linux Subsystem

Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

**Comment by kmuriki** [comment]
Closing these old issues in the old Singularity repo. If this issue is still relevant please create a new issue under the Apptainer repo. Thanks.
