### ISSUE TITLE
Pull from OCI source does not work unless target sif is specified

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#2018]
Hi @bauerm97 - I missed this in my testing of #2012 I'm afraid...

If you pull without a target sif filename... it doesn't work...

```
08:54 PM $ singularity -d pull docker://ubuntu
DEBUG   [U=1000,P=7106]    NewBundle()                   Created temporary directory for bundle /tmp/sbuild-689967288
INFO    [U=1000,P=7106]    Full()                        Starting build...
DEBUG   [U=1000,P=7106]    updateCacheSubdir()           Caching directory set to /home/dave/.singularity/cache/oci
Getting image source signatures
Skipping fetch of repeat blob sha256:124c757242f88002a858c23fc79f8262f9587fa30fd92507e586ad074afb42b6
Skipping fetch of repeat blob sha256:9d866f8bde2a0d607a6d17edc0fbd5e00b58306efc2b0a57e0ba72f269e7c6be
Skipping fetch of repeat blob sha256:fa3f2f277e67c5cbbf1dac21dc27111a60d3cd2ef494d94aa1515d3319f2a245
Skipping fetch of repeat blob sha256:398d32b153e84fe343f0c5b07d65e89b05551aae6cb8b3a03bb2b662976eb3b8
Skipping fetch of repeat blob sha256:afde35469481d2bc446d649a7a3d099147bbf7696b66333e76a411686b617ea1
Copying config sha256:eaed126a557b4b992c2368ae07586921ecc1cf58eefdfd8dc82ea4f67efcfb11
 2.62 KiB / 2.62 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG   [U=1000,P=7106]    Full()                        Calling assembler
INFO    [U=1000,P=7106]    Assemble()                    Creating sandbox directory...
DEBUG   [U=1000,P=7106]    Assemble()                    Moving sandbox from /tmp/sbuild-689967288/fs to
ERROR   [U=1000,P=7106]    Assemble()                    Sandbox Assemble Failed: mkdir : no such file or directory
FATAL   [U=1000,P=7106]    PullOciImage()                Unable to pull docker://ubuntu: mkdir : no such file or directory
```

If you specify an explicity target sif then it does work:

```
08:56 PM $ singularity -d pull test.sif docker://ubuntu
DEBUG   [U=1000,P=7140]    NewBundle()                   Created temporary directory for bundle /tmp/sbuild-168567221
INFO    [U=1000,P=7140]    Full()                        Starting build...
DEBUG   [U=1000,P=7140]    updateCacheSubdir()           Caching directory set to /home/dave/.singularity/cache/oci
Getting image source signatures
Skipping fetch of repeat blob sha256:124c757242f88002a858c23fc79f8262f9587fa30fd92507e586ad074afb42b6
Skipping fetch of repeat blob sha256:9d866f8bde2a0d607a6d17edc0fbd5e00b58306efc2b0a57e0ba72f269e7c6be
Skipping fetch of repeat blob sha256:fa3f2f277e67c5cbbf1dac21dc27111a60d3cd2ef494d94aa1515d3319f2a245
Skipping fetch of repeat blob sha256:398d32b153e84fe343f0c5b07d65e89b05551aae6cb8b3a03bb2b662976eb3b8
Skipping fetch of repeat blob sha256:afde35469481d2bc446d649a7a3d099147bbf7696b66333e76a411686b617ea1
Copying config sha256:eaed126a557b4b992c2368ae07586921ecc1cf58eefdfd8dc82ea4f67efcfb11
 2.62 KiB / 2.62 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
DEBUG   [U=1000,P=7140]    Full()                        Calling assembler
INFO    [U=1000,P=7140]    Assemble()                    Creating sandbox directory...
DEBUG   [U=1000,P=7140]    Assemble()                    Moving sandbox from /tmp/sbuild-168567221/fs to test.sif
INFO    [U=1000,P=7140]    Full()                        Build complete!
```

Expect it to generate a default filename, like it does for a library pull in 3.0 (or for any pull in 2.x):

```
$ singularity pull library://dtrudg/linux/ubuntu:17.10
INFO:    Download filename not provided. Downloading to: ubuntu_17.10.sif
 34.77 MiB / 34.77 MiB [======================================================================================] 100.00% 10.17 MiB/s 3s
```

**Comment by dtrudg** [comment]
oh - hold on... that's pulling into a sandbox, not a sif too. Was expecting a sif out here also.

**Comment by GodloveD** [comment]
There seems to be another issue.  Don't know if it is related or if I should open another issue.
```
$ singularity shell docker://godlovedc/lolcow
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
Skipping fetch of repeat blob sha256:3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
Skipping fetch of repeat blob sha256:9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
Skipping fetch of repeat blob sha256:d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
Skipping fetch of repeat blob sha256:7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
Skipping fetch of repeat blob sha256:8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
Copying config sha256:73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
 3.33 KiB / 3.33 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
FATAL:   Unable to build: while creating container: container file creation failed: open /home/david/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb/godlovedc/lolcow: no such file or directory
```

**Comment by jmstover** [comment]
@GodloveD ... @ArangoGutierrez  and I are talking through that one currently.

**Comment by dtrudg** [comment]
Confirm the above too... am a little concerned now that the test suite didn't catch these? Are these tests existent but comment out.. from the translation work that Ad did previously? Also... I swear the above worked when I tested the PR... result of stuff merged back in, or maybe I missed the last commits of the PR :-(

**Comment by jmstover** [comment]
@dctrud I think the tests are pulling from like: `docker://alpine` ... It's a single level.  When I tested the PR I used that and `docker://httpd` ... but not one that was more than that. :/

**Comment by dtrudg** [comment]
@jmstover - good spot... I tried lolcow at some point (this AM before a lot of commits), but looking in bash history.... yes, I used alpine on last check of the PR!

**Comment by jmstover** [comment]
@ArangoGutierrez is working on a PR that will convert `/` -> `_` in the image name. That should fix the error @GodloveD reported.

**Comment by dtrudg** [comment]
:+1: - think you just found the bit I came across :-)

**Comment by bauerm97** [comment]
Yea I didn't fix that yet in my PR. The way Uris/file names were being handled in the pull command was badly written so I'm working on a second PR to fix this. Didn't want to make this PR too bloated. Next PR will handle running from library images directly and better syntax handling for the pull command. Also will change pull to pull into a sif, that was a bit of an oversight

**Comment by bauerm97** [comment]
I think what DG caught is actually something I missed. I'll include in next PR as well. Should be an easy fix

**Comment by bauerm97** [comment]
Fixed via #2019
