### ISSUE TITLE
3.0: Various issues building RPMs with provided scripts

### ISSUE THREAD

**Issue by fearful-symmetry** [apptainer/singularity#2149]
## Version of Singularity:

v3.0.0-beta.1
Run on Fedora 28
rpmbuild version 4.14.2

### Expected behavior
I run `./mconfig` and `./buildrpm` and it builds the RPM

### Actual behavior
I ran into a number of issues building singularity with the provided scripts. Considering how terrible rpmbuild is in general, it's possible that some of these are my fault. However, I don't usually run into this many problems building from upstream specfiles.

First of all, the specfile generated my `mconfig` leaves the `Version` field empty, so you need to populate it yourself:
```
Version: v3.0.0_beta.1
```
Second, I ran into a bunch of `*** ERROR: No build ID note found in ...` errors while running the `/usr/lib/rpm/find-debuginfo.sh ` portion of the script, that finally ended in
```
/usr/lib/rpm/find-debuginfo.sh: line 475: /tmp/find-debuginfo.z7eLF1/res.*: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.uCRt44 (%install)
```

I just added `%define debug_package %{nil}` to the spec file to keep things moving along, although this probably isn't the proper solution.
 
On the next build attempt, I ran into this error, which is where I am now:

```
warning: Duplicate build-ids /home/USER/rpmbuild/BUILDROOT/singularity-v3.0.0_beta.1-1.fc28.x86_64/usr/libexec/singularity/bin/starter-suid and /home/USER/rpmbuild/BUILDROOT/singularity-v3.0.0_beta.1-1.fc28.x86_64/usr/libexec/singularity/bin/starter
Provides: config(singularity) = v3.0.0_beta.1-1.fc28 singularity = v3.0.0_beta.1-1.fc28 singularity(x86-64) = v3.0.0_beta.1-1.fc28 singularity-runtime
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /bin/sh libc.so.6()(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libdl.so.2()(64bit) libdl.so.2(GLIBC_2.2.5)(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) libpthread.so.0(GLIBC_2.3.2)(64bit) rtld(GNU_HASH)
Obsoletes: singularity-runtime
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/USER/rpmbuild/BUILDROOT/singularity-v3.0.0_beta.1-1.fc28.x86_64
error: Installed (but unpackaged) file(s) found:
   /libexec/singularity/cni/bandwidth
   /libexec/singularity/cni/bridge
   /libexec/singularity/cni/dhcp
   /libexec/singularity/cni/flannel
   /libexec/singularity/cni/host-device
   /libexec/singularity/cni/host-local
   /libexec/singularity/cni/ipvlan
   /libexec/singularity/cni/loopback
   /libexec/singularity/cni/macvlan
   /libexec/singularity/cni/portmap
   /libexec/singularity/cni/ptp
   /libexec/singularity/cni/static
   /libexec/singularity/cni/tuning
   /libexec/singularity/cni/vlan
```

### Steps to reproduce behavior
Download the 3.0 beta, run `./mconfig` then ` cd dist/rpm && ./buildrpm`

**Comment by fearful-symmetry** [comment]
So the `installed but unpackaged files found` error is part of the Fascist Build Policy (not my name) and can be disabled with `%define _unpackaged_files_terminate_build 0` 

That being said, I don't know enough about to singularity backend to know if we want those files bundled in the rpm. Considering the file path, we presumably do?

**Comment by bauerm97** [comment]
@jmstover

**Comment by DrDaveD** [comment]
Most of the issues are being addressed in pr #2048.

The version number should not be empty, however.  I suppose it would be though if you try to compile from an area that wasn't created with git clone, following the instructions in INSTALL.md.

**Comment by fearful-symmetry** [comment]
Ah, good to see! 

I'm used to seeing install docs in either the main readme or in a link in the main readme (or just running `go get`), so I just overlooked the `INSTALL.md` and built from the tarfile release instead of pulling down the tag for the beta release. Downloading tar files is probably a very un-go way to do things, now that I think of it. Just to be on the safe side, I'll avoid closing the issue until #2048 is merged.

**Comment by DrDaveD** [comment]
The missing version is also reported in issue #2120.

**Comment by DrDaveD** [comment]
#2048 was merged, but rpm building was promptly broken by #2185.   #2185 intentionally affected rpm building but didn't compensate for it in the rpm packaging files.  The rpm packaging files are fixed again as part of #2202.

**Comment by yhcote** [comment]
@DrDaveD : 2185's "Intention" was to FIX in a better way than stripping all symbols of all builds and every packages by introducing a notion of config profile. 

Simply: ./mconfig -P release-stripped, is to be run before running the rpmbuild script.

Is there something else I am missing?

**Comment by DrDaveD** [comment]
@yhcote Yes I know, I had that in there first, but I found a better way, the last commit
36f05c8 of #2202 enables the build to work without stripping.  I know that #2185's intention was to make a better way to strip, but it did it without fixing singularity.spec at the same time, so the result was that rpm building broke.

**Comment by DrDaveD** [comment]
#2202 is merged now, I think this ticket can be closed.

**Comment by fearful-symmetry** [comment]
Alas, rpmbuild is still failing:

```

RPM build errors:
    Duplicate build-ids /home/user/rpmbuild/BUILDROOT/singularity-v3.0.0-51_g9503e53c.fc28.x86_64/usr/libexec/singularity/bin/starter-suid and /home/user/rpmbuild/BUILDROOT/singularity-v3.0.0-51_g9503e53c.fc28.x86_64/usr/libexec/singularity/bin/starter
    Empty %files file /home/user/rpmbuild/BUILD/singularity-v3.0.0/debugsourcefiles.list
```

This is with a fresh clone of the latest commit:
```
 git show
commit 9503e53cd75d618c7982209da4fbe4fdaf2bbe18 (HEAD -> master, origin/master, origin/HEAD)
Merge: f86a7721 fa6c9ef9
Author: yhcote <yhcote@users.noreply.github.com>
Date:   Mon Oct 15 12:55:25 2018 -0700

    Merge pull request #2226 from jmstover/rpm_fix
    
    Fix RPM building with buildrpm script
```

**Comment by jscook2345** [comment]
We just merged in an RPM `makefile` target that is described in the INSTALL.md. Can you check that out and see if it fixes your issues?

**Comment by fearful-symmetry** [comment]
So, on the newest build I still can't build it on Fedora, but it builds fine on Centos. Centos is using a slightly older version of rpmbuild (4.11.3) that might explain this.

**Comment by DrDaveD** [comment]
I was able to reproduce it in a Fedora docker container, fixed in #2256.
