### ISSUE TITLE
examples/arch.def on master branch is corrupted due to some merging errors

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#261]
A side effect of  "Merge remote-tracking branch 'origin' into 2.x" activity apparently.

**Comment by gmkurtzer** [comment]
I think this has been fixed at this point. Can you please confirm and close if so?

Thanks!

**Comment by czka** [comment]
@gmkurtzer It's not fixed.

My last commit to `arch.def` on **master** branch was on Sep 9. You accepted that in my PR to **master** on Sep 10: https://github.com/singularityware/singularity/pull/208.

On Sep 13 I commited some cleanup fixes to **2.x** branch. You accepted my PR to **2.x** on Sep 14: https://github.com/singularityware/singularity/pull/214.

Then go your commits to both **master** and **2.x** branch, with the 44e24affad2a039ae27b2350fb6c2912fe83dbd8 _"Merge remote-tracking branch 'origin' into 2.x"_ activity amongst them. The following conflicts were involved:

> 	**examples/arch.def**
> 	libexec/bootstrap/modules-v1/arch.sh
> 	libexec/mods/Makefile.am

That's where your merging error in `arch.def` happened.

As it is now, `arch.def`, both on **2.x** and **master**, is a mix of the old and new definition format. I don't know exactly what you meant to achieve at that point, so I'd rather leave fixing that to you.

**Comment by vsoch** [comment]
@czka I started looking into this - just ran into a snag but will hopefully be able to help soon! It looks like the file just has two different bootstrap versions in it, so we just need to simplify it. Once I get through the snag (just opened an issue) I should be able to test and provide a suggested update for the file.

**Comment by gmkurtzer** [comment]
Closing old issues.
