### ISSUE TITLE
What is the --json option for singularity inspect used for?

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3053]
## Version of Singularity:

3.1.0

* Regular output, looks like reasonable json!
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect alpine_latest.sif

{
        "org.label-schema.build-date": "Thursday_21_March_2019_15:15:0_EDT",
        "org.label-schema.schema-version": "1.0",
        "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
        "org.label-schema.usage.singularity.deffile.from": "alpine:latest",
        "org.label-schema.usage.singularity.version": "3.1-1.el6"
}
</pre>

* JSON output, looks worse with escapes that are not needed?
<pre>
[justin@ip-172-31-94-96 inspect]$ singularity inspect --json alpine_latest.sif
{
        "attributes": {
                "labels": "{\n\t\"org.label-schema.build-date\": \"Thursday_21_March_2019_15:15:0_EDT\",\n\t\"org.label-schema.schema-version\": \"1.0\",\n\t\"org.label-schema.usage.singularity.deffile.bootstrap\": \"docker\",\n\t\"org.label-schema.usage.singularity.deffile.from\": \"alpine:latest\",\n\t\"org.label-schema.usage.singularity.version\": \"3.1-1.el6\"\n}"
        },
        "type": "container"
}
</pre>

I see when you add other options it puts them into JSON. But why is that done?

see also: https://github.com/sylabs/singularity/issues/2148

**Comment by vsoch** [comment]
The default output used to *not* be json - it was intended for a human to read. At some point this was changed, and now since it's default this is why the --json option doesn't seem useful.  I've also opened an issue to note that the output is wrong - it should conform to the JSON API spec (with data at the highest level) but this was chopped off.

**Comment by vsoch** [comment]
See https://github.com/sylabs/singularity/issues/2790

**Comment by vsoch** [comment]
It looks like there is another bug that if you add --json, it ignores the default output (labels, as shown in the first) and spits out the remainder of the fields.

**Comment by mem** [comment]
Checking 3.4, it looks like this:

```
$ builddir/singularity pull --force alpine:3.9
INFO:    Downloading library image
 2.59 MiB / 2.59 MiB [==================================================================================================================================================] 100.00% 3.10 MiB/s 0s
WARNING: Container might not be trusted; run 'singularity verify alpine_3.9.sif' to show who signed it
INFO:    Download complete: alpine_3.9.sif

$ builddir/singularity inspect ./alpine_3.9.sif
==labels==
org.label-schema.build-date: Tuesday_26_March_2019_11:59:18_PDT
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: localimage
org.label-schema.usage.singularity.deffile.from: alpine-sand/
org.label-schema.usage.singularity.version: 3.1.0-542.g962042cbb

$ builddir/singularity inspect --json ./alpine_3.9.sif
{
        "attributes": {
                "apps": "",
                "labels": {
                        "org.label-schema.build-date": "Tuesday_26_March_2019_11:59:18_PDT",
                        "org.label-schema.schema-version": "1.0",
                        "org.label-schema.usage.singularity.deffile.bootstrap": "localimage",
                        "org.label-schema.usage.singularity.deffile.from": "alpine-sand/",
                        "org.label-schema.usage.singularity.version": "3.1.0-542.g962042cbb"
                }
        },
        "type": "container"
}
```

so it looks like this is fixed? Please reopen if not.

**Comment by vsoch** [comment]
Sorry this is still incorrect - there is a missing "data" field to hold "attributes" as a child, alongside type. It was removed in the Singularity to Go migration and not restored, see https://jsonapi.org/format/

**Comment by mem** [comment]
I thought the original issue was about the weird output. Isn't the other issue the one about the wrong schema?

**Comment by vsoch** [comment]
If we can link the other issue here for users like me (that confused the two) then we can close again -  this was my mistake in mixing up the issues,  because the second inspection that uses json is still wrong.

**Comment by vsoch** [comment]
See https://github.com/sylabs/singularity/issues/2790 for the schema issue, and note  the example above is not correct still.  However this particular issue about the default format is fixed, closing.
